CREATE DATABASE CADASTRO;
USE CADASTRO;

CREATE TABLE CLIENTE(
	ID INT NOT NULL AUTO_INCREMENT,
    NOME CHAR(50),
    ENDERECO CHAR(35),
    TELEFONE CHAR(12),
    EMAIL CHAR(40),
    PRIMARY KEY(ID)
);

SELECT * FROM CLIENTE;


CREATE TABLE VEICULOS(
	ID INT NOT NULL AUTO_INCREMENT,
	MARCA CHAR(20),
	MODELO CHAR(20),
	ANO CHAR(4),
    DISPONIBILIDADE CHAR(1),
    PRIMARY KEY (ID)
);

SELECT * FROM VEICULOS;

CREATE TABLE RESERVAS(
ID INT NOT NULL AUTO_INCREMENT,
CLIENTE INT,
VEICULO INT,
DATA_INICIO DATE,
DATA_FIM DATE,
FOREIGN KEY (CLIENTE) REFERENCES CLIENTE(ID),
FOREIGN KEY (VEICULO) REFERENCES VEICULOS(ID),
PRIMARY KEY (ID)
);

SELECT * FROM RESERVAS;

SELECT C.ID,C.NOME AS NOME_CLIENTE, V.ID AS ID_CARRO,V.MARCA, V.MODELO, R.DATA_INICIO, R.DATA_FIM
FROM RESERVAS R
JOIN CLIENTE C ON R.CLIENTE = C.ID
JOIN VEICULOS V ON R.VEICULO = V.ID
 ORDER BY NOME_CLIENTE ASC;	







